import type { Course } from "@/types/course";
import { delay } from "./delay";

const INSTRUCTOR = "Dr Ahmed Habib";
const INSTRUCTOR_TITLE = "CPHQ, Healthcare Quality Director";

const store: Course[] = [
  {
    id: "1",
    title: "CPHQ Comprehensive Review 2024",
    tag: "Exam Prep",
    rating: 4.9,
    reviewCount: 128,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 12.5,
    enrolledCount: 1240,
    priceRegular: 249.99,
    priceSale: 199.99,
    level: "Intermediate",
    certificationType: "CPHQ Prep",
  },
  {
    id: "2",
    title: "Quality Improvement Methodologies",
    tag: "Quality Management",
    rating: 4.8,
    reviewCount: 94,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 8,
    enrolledCount: 892,
    priceRegular: 199.99,
    priceSale: 149.99,
    level: "Intermediate",
    certificationType: "CME Credits",
  },
  {
    id: "3",
    title: "Patient Safety Fundamentals",
    tag: "Free Resource",
    rating: 4.7,
    reviewCount: 256,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 4,
    enrolledCount: 2100,
    priceRegular: 0,
    level: "Beginner",
  },
  {
    id: "4",
    title: "Advanced Healthcare Analytics",
    tag: "Advanced",
    rating: 4.9,
    reviewCount: 72,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 15,
    enrolledCount: 456,
    priceRegular: 299.99,
    priceSale: 249.99,
    level: "Advanced",
    certificationType: "Micro-Credential",
  },
  {
    id: "5",
    title: "Data Analysis for Quality Teams",
    tag: "Data Analysis",
    rating: 4.6,
    reviewCount: 58,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 6,
    enrolledCount: 534,
    priceRegular: 179.99,
    priceSale: 139.99,
    level: "Intermediate",
  },
  {
    id: "6",
    title: "Regulatory Compliance in Healthcare",
    tag: "Compliance",
    rating: 4.8,
    reviewCount: 89,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 10,
    enrolledCount: 678,
    priceRegular: 219.99,
    priceSale: 179.99,
    level: "Advanced",
    certificationType: "CME Credits",
  },
  {
    id: "7",
    title: "CPHQ Practice Exams & Strategies",
    tag: "Exam Prep",
    rating: 4.9,
    reviewCount: 201,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 5,
    enrolledCount: 1580,
    priceRegular: 199.99,
    priceSale: 159.99,
    level: "Intermediate",
    certificationType: "CPHQ Prep",
  },
  {
    id: "8",
    title: "Root Cause Analysis in Healthcare",
    tag: "Quality Management",
    rating: 4.7,
    reviewCount: 112,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 3,
    enrolledCount: 723,
    priceRegular: 149.99,
    priceSale: 119.99,
    level: "Beginner",
  },
  {
    id: "9",
    title: "Patient Safety Culture",
    tag: "Patient Safety",
    rating: 4.8,
    reviewCount: 67,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 4.5,
    enrolledCount: 445,
    priceRegular: 169.99,
    priceSale: 129.99,
    level: "Intermediate",
  },
  {
    id: "10",
    title: "CPHQ Exam Simulation Pack",
    tag: "Exam Prep",
    rating: 4.9,
    reviewCount: 312,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 6,
    enrolledCount: 1890,
    priceRegular: 229.99,
    priceSale: 189.99,
    level: "Intermediate",
    certificationType: "CPHQ Prep",
  },
  {
    id: "11",
    title: "Quality Tools Workshop",
    tag: "Quality Management",
    rating: 4.6,
    reviewCount: 45,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 7,
    enrolledCount: 312,
    priceRegular: 189.99,
    level: "Advanced",
  },
  {
    id: "12",
    title: "Introduction to CPHQ",
    tag: "Free Resource",
    rating: 4.7,
    reviewCount: 189,
    instructorName: INSTRUCTOR,
    instructorTitle: INSTRUCTOR_TITLE,
    durationHours: 2,
    enrolledCount: 2340,
    priceRegular: 0,
    level: "Beginner",
  },
];

function clone<T>(data: T): T {
  return JSON.parse(JSON.stringify(data));
}

export async function getCourses(): Promise<Course[]> {
  await delay(200);
  return clone(store);
}

export async function getCourseById(id: string): Promise<Course | null> {
  await delay(100);
  const course = store.find((c) => c.id === id);
  return course ? clone(course) : null;
}
